name: Tests

on:
  push:
    branches: [feature-app-tests]
  pull_request:
    branches: [feature-app-tests]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependsncies
        run: npm ci
      - name: Run tests
        run: npm test
